# Generated by Django 3.2 on 2021-04-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
