# Generated by Django 3.2 on 2021-05-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
