# Generated by Django 3.2 on 2021-05-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hospital',
            table='Hospital',
        ),
    ]
