# Generated by Django 3.2 on 2021-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_alter_doctor_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="Photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctor_profile"),
        ),
    ]
