# Generated by Django 3.2 on 2021-05-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
